name: Test Action

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: daniele-tentoni/gradle-wrapper-example/.github/workflows/test-app.yml@main

  release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ github.token }}

      - name: Release using Semantic Releasing
        run: |
          npm install
          npx semantic-release
        env:
          GH_TOKEN: ${{ github.token }}
