name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: daniele-tentoni/gradle-wrapper-example/.github/workflows/test-app.yml@main

  release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Release using Semantic Releasing
        run: |
          npm install
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
